import { PERMISSIONS } from '~/config/constants'

export const categories = [
  {
    discipline_id: 1,
    discipline_name: 'Project Management',
    discipline_image: '/public/images/icons/categories/project-management.png',
    discipline_url: 'project-management',
    active: true,
    permissions: PERMISSIONS.TCT_PROJECT_MANAGEMENT,
  },
  {
    discipline_id: 2,
    discipline_name: 'OHS',
    discipline_image: '/public/images/icons/categories/she.png',
    discipline_url: 'OHS',
    active: true,
    permissions: PERMISSIONS.TCT_OHS,
  },
  {
    discipline_id: 3,
    discipline_name: 'Engineering',
    discipline_image: '/public/images/icons/categories/engineering.png',
    discipline_url: 'engineering',
    active: true,
    permissions: PERMISSIONS.TCT_ENGINEERING,
  },
  {
    discipline_id: 4,
    discipline_name: 'Procurement',
    discipline_image: '/public/images/icons/categories/procurement.png',
    discipline_url: 'procurement',
    active: true,
    permissions: PERMISSIONS.TCT_PROCUREMENT,
  },
  {
    discipline_id: 5,
    discipline_name: 'Construction',
    discipline_image: '/public/images/icons/categories/construction.png',
    discipline_url: 'construction',
    active: true,
    permissions: PERMISSIONS.TCT_CONSTRUCTION,
  },
  {
    discipline_id: 6,
    discipline_name: 'Precom-Comm',
    discipline_image: '/public/images/icons/categories/precom-comm.png',
    discipline_url: 'precom-comm',
    active: true,
    permissions: PERMISSIONS.TCT_PRECOM_COMM,
  },
  {
    discipline_id: 7,
    discipline_name: 'Internal Report & Financial',
    discipline_image: '/public/images/icons/categories/financial.png',
    discipline_url: 'internal-report-financial',
    active: true,
    permissions: PERMISSIONS.TCT_FINANCIAL,
  },
  {
    discipline_id: 8,
    discipline_name: 'Quality',
    discipline_image: '/public/images/icons/categories/quality.png',
    discipline_url: 'quality',
    active: true,
    permissions: PERMISSIONS.TCT_QUALITY,
  },
  {
    discipline_id: 9,
    discipline_name: 'Schedule',
    discipline_image: '/public/images/icons/categories/schedule.png',
    discipline_url: 'schedule',
    active: true,
    permissions: PERMISSIONS.TCT_SCHEDULE,
  },
  {
    discipline_id: 10,
    discipline_name: 'Contractual',
    discipline_image: '/public/images/icons/categories/contractual.png',
    discipline_url: 'contractual',
    active: true,
    permissions: PERMISSIONS.TCT_CONTRACTUAL,
  },
  {
    discipline_id: 11,
    discipline_name: 'Risk',
    discipline_image: '/public/images/icons/categories/risk.png',
    discipline_url: 'risk',
    active: true,
    permissions: PERMISSIONS.TCT_RISK,
  },
  {
    discipline_id: 12,
    discipline_name: 'Weather',
    discipline_image: '/public/images/icons/categories/weather.png',
    discipline_url: 'weather',
    active: true,
    permissions: PERMISSIONS.TCT_WEATHER,
  },
  {
    discipline_id: 13,
    discipline_name: 'Photos',
    discipline_image: '/public/images/icons/categories/photos.png',
    discipline_url: 'photos',
    active: true,
    permissions: PERMISSIONS.TCT_PHOTOS,
  },
  {
    discipline_id: 14,
    discipline_name: 'Esg Dashboard',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'esg-dashboard',
    active: true,
    permissions: PERMISSIONS.TCT_ESG_DASHBOARD,
  },
  {
    discipline_id: 15,
    discipline_name: 'Material Management',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'material-management',
    active: true,
    permissions: PERMISSIONS.TCT_MATERIAL_MANAGEMENT,
  },
  {
    discipline_id: 16,
    discipline_name: 'Corporate Manpower Dashboard',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'corporate-manpower-dashboard',
    active: true,
    permissions: PERMISSIONS.TCT_CORPORATE_MANPOWER_DASHBOARD,
  },
  {
    discipline_id: 17,
    discipline_name: 'Standard Norm',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'standard-norm',
    active: true,
    permissions: PERMISSIONS.TCT_STANDARD_NORM,
  },
  {
    discipline_id: 18,
    discipline_name: 'Corporate MMR Dashboard',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'corporate-mmr-dashboard',
    active: true,
    permissions: PERMISSIONS.TCT_CORPORATE_MMR_DASHBOARD,
  },
  {
    discipline_id: 19,
    discipline_name: 'Project Risk Management',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'project-risk-management',
    active: true,
    permissions: PERMISSIONS.TCT_PROJECT_RISK_MANAGEMENT,
  },
  {
    discipline_id: 20,
    discipline_name: 'ISR Monitoring',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'isr-monitoring',
    active: true,
    permissions: PERMISSIONS.TCT_ISR_MONITORING,
  },
  {
    discipline_id: 21,
    discipline_name: 'Badan Pusat Statistic',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'badan-pusat-statistic',
    active: true,
    permissions: PERMISSIONS.TCT_BADAN_PUSAT_STATISTIC,
  },
  {
    discipline_id: 22,
    discipline_name: 'Weekly Dashboard',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'weekly-dashboard',
    active: true,
    permissions: PERMISSIONS.TCT_WEEKLY_DASHBOARD,
  },
  {
    discipline_id: 23,
    discipline_name: 'External Dashboard',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'external-dashboard',
    active: true,
    permissions: PERMISSIONS.TCT_EXTERNAL_DASHBOARD,
  },
  {
    discipline_id: 24,
    discipline_name: 'Phoenix Steering Committee',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'phoenix-steerings-committee',
    active: true,
    permissions: PERMISSIONS.TCT_PHOENIX_STEERING_COMMITTEE,
  },
  {
    discipline_id: 25,
    discipline_name: 'Others',
    discipline_image: '/public/images/icons/subcategories/general.png',
    discipline_url: 'phoenix-steerings-committee',
    active: true,
    permissions: PERMISSIONS.TCT_PHOENIX_STEERING_COMMITTEE,
  },
]

export const customOrder = [
  'OHS',
  'Project Management',
  'Engineering',
  'Procurement',
  'Construction',
  'Precom Comm',
  'Internal Report & Financial',
  'Quality',
  'Schedule',
  'Contractual',
  'Risk',
]
