export const LOCAL_STORAGE_KEY_USER = 'USER_DATA'

export const PERMISSIONS = {
  TCT_PROJECT_MANAGEMENT: 'TCT_PROJECT_MANAGEMENT',
  TCT_OHS: 'TCT_OHS',
  TCT_ENGINEERING: 'TCT_ENGINEERING',
  TCT_PROCUREMENT: 'TCT_PROCUREMENT',
  TCT_CONSTRUCTION: 'TCT_CONSTRUCTION',
  TCT_PRECOM_COMM: 'TCT_PRECOM_COMM',
  TCT_FINANCIAL: 'TCT_INTERNAL_REPORT_&_FINANCIAL',
  TCT_QUALITY: 'TCT_QUALITY',
  TCT_SCHEDULE: 'TCT_SCHEDULE',
  TCT_CONTRACTUAL: 'TCT_CONTRACTUAL',
  TCT_RISK: 'TCT_RISK',
  TCT_WEATHER: 'TCT_WEATHER',
  TCT_PHOTOS: 'TCT_PHOTOS',
  TCT_ESG_DASHBOARD: 'TCT_ESG_DASHBOARD',
  TCT_MATERIAL_MANAGEMENT:'TCT_MATERIAL_MANAGEMENT',
  TCT_CORPORATE_MANPOWER_DASHBOARD:'TCT_CORPORATE_MANPOWER_DASHBOARD',
  TCT_STANDARD_NORM:'TCT_STANDARD_NORM',
  TCT_CORPORATE_MMR_DASHBOARD:'TCT_CORPORATE_MMR_DASHBOARD',
  TCT_PROJECT_RISK_MANAGEMENT:'TCT_PROJECT_RISK_MANAGEMENT',
  TCT_ISR_MONITORING:'TCT_ISR_MONITORING',
  TCT_BADAN_PUSAT_STATISTIC:'TCT_BADAN_PUSAT_STATISTIC',
  TCT_WEEKLY_DASHBOARD:'TCT_WEEKLY_DASHBOARD',
  TCT_EXTERNAL_DASHBOARD:'TCT_EXTERNAL_DASHBOARD',
  TCT_PHOENIX_STEERING_COMMITTEE:'TCT_PHOENIX_STEERING_COMMITTEE'
}