export const subcategories = [
  {
    'discipline_id': 1,
    'discipline_name': 'Structure Erection',
    'discipline_image': '/public/images/icons/subcategories/structure-erection.png',
    'discipline_url': 'structure-erection',
    'active': true,
  },
  {
    'discipline_id': 2,
    'discipline_name': 'Construction Piping',
    'discipline_image': '/public/images/icons/subcategories/construction-piping.png',
    'discipline_url': 'construction-piping',
    'active': true,
  },
  {
    'discipline_id': 3,
    'discipline_name': 'Mechanical Rotating',
    'discipline_image': '/public/images/icons/subcategories/mechanical-rotating.png',
    'discipline_url': 'mechanical-rotating',
    'active': true,
  },
  {
    'discipline_id': 4,
    'discipline_name': 'Mechanical Static',
    'discipline_image': '/public/images/icons/subcategories/mechanical-static.png',
    'active': false,
  },
  {
    'discipline_id': 5,
    'discipline_name': 'Electrical',
    'discipline_image': '/public/images/icons/subcategories/electrical.png',
    'discipline_url': 'electrical',
    'active': false,
  },
  {
    'discipline_id': 6,
    'discipline_name': 'Instrumentation & Telecomm.',
    'discipline_image': '/public/images/icons/subcategories/instrumen-telec.png',
    'discipline_url': 'instrument-telecomm',
    'active': false,
  },
  {
    'discipline_id': 7,
    'discipline_name': 'General',
    'discipline_image': '/public/images/icons/subcategories/general.png',
    'discipline_url': 'general',
    'active': false,
  },
  {
    'discipline_id': 8,
    'discipline_name': 'Civil',
    'discipline_image': '/public/images/icons/subcategories/civil.png',
    'discipline_url': 'civil',
    'active': false,
  },
  {
    'discipline_id': 9,
    'discipline_name': 'Concrete Structure',
    'discipline_image': '/public/images/icons/subcategories/concrete-structure.png',
    'discipline_url': 'concrete-structure',
    'active': false,
  },
  {
    'discipline_id': 10,
    'discipline_name': 'Building',
    'discipline_image': '/public/images/icons/subcategories/building.png',
    'discipline_url': 'building',
    'active': false,
  },
  {
    'discipline_id': 11,
    'discipline_name': 'Offshore',
    'discipline_image': '/public/images/icons/subcategories/offshore.png',
    'discipline_url': 'offshore',
    'active': false,
  },
  {
    'discipline_id': 12,
    'discipline_name': 'Insulation',
    'discipline_image': '/public/images/icons/subcategories/insulation.png',
    'discipline_url': 'insulation',
    'active': false,
  },
  {
    'discipline_id': 13,
    'discipline_name': 'Painting',
    'discipline_image': '/public/images/icons/subcategories/painting.png',
    'discipline_url': 'painting',
    'active': false,
  },
  {
    'discipline_id': 14,
    'discipline_name': 'Pipeline',
    'discipline_image': '/public/images/icons/subcategories/pipeline.png',
    'discipline_url': 'pipeline',
    'active': false,
  },
]