name: Build and deploy static site to Azure Web App - misi-emas-masmindo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: static-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: static-dist
          path: dist

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'misi-emas-masmindo'
          slot-name: 'Production'
          package: dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38486A016C6E4195871D3C742B97FA89 }}
