name: Build and deploy static site to Azure Web App - misi-emas-masmindo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout your repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Node/Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      # 3️⃣ Install and build
      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      # 4️⃣ Upload build folder as artifact
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1️⃣ Download build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # 2️⃣ Deploy only the built static files
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'misi-emas-masmindo'
          slot-name: 'Production'
          package: './dist'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38486A016C6E4195871D3C742B97FA89 }}
